### ISSUE TITLE
안녕하세요 프로젝트인에 대해 궁금합니다.

### ISSUE THREAD

**Issue by aptheparker** [hwan-2/eighteen#1]
1. 이 프로젝트는 오픈소스가 맞는지 궁금합니다. 다른 개발자들도 참여가 가능한 프로젝트일까요?
2. 제가 개인적으로 이 프로젝트에 관심이 있는데 혹시 참여가 가능할까요?

답변주시면 감사하겠습니다.

**Comment by SultanLee** [comment]
안녕하세요 저희 프로젝트에 대해 관심을 가져주셔서 감사합니다.
제가 지금 투병중이라 답변에 늦은점 고려해주시기 바랍니다.

1. 오픈소스가 맞습니다. MIT라이센스를 추가해 두었습니다.
2. 현재 저희 프로젝트는 아직 개발 중에 있으며, 그 과정에서 미리 구성된 팀원 개인의 역량 발전 및 학습 목적으로 진행되고 있어서, 외부 참여자의 추가가 어려운 상황입니다. 하지만 저희 프로젝트에 관심을 가져주신 점 감사드립니다.

감사합니다.

**Comment by aptheparker** [comment]
확인했습니다~
답변 감사드립니다!

프로젝트 힘내시고 같이 협력할 다음 오픈소스가 있기를 바랍다!
